{
  "comments": [
    {
      "key": {
        "uuid": "4d74f5bd_78866b68",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 10,
      "author": {
        "id": 1052644
      },
      "writtenOn": "2019-11-25T15:48:20Z",
      "side": 1,
      "message": "Could you also reference Bug 129332183 here?",
      "range": {
        "startLine": 10,
        "startChar": 0,
        "endLine": 10,
        "endChar": 14
      },
      "revId": "71054fad6000ee3fccbcb20904ffef13ea9a8664",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    }
  ]
}