{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "2d95f56a_e504d03f",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1894735
      },
      "writtenOn": "2024-05-02T09:08:12Z",
      "side": 1,
      "message": "Thanks!",
      "revId": "748cb28104cd48363307d455111a9d5710d953df",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "8ee50203_15823230",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1975620
      },
      "writtenOn": "2024-05-02T12:48:56Z",
      "side": 1,
      "message": "I see there has been a test failure. We don\u0027t seem to have any failures on our side - please if you could let me know which test is failing I will investigate, thanks!",
      "revId": "748cb28104cd48363307d455111a9d5710d953df",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}